//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class adherent
    {
        public adherent()
        {
            this.emprunts = new HashSet<emprunt>();
        }
    
        public int codeA { get; set; }
        public string nomA { get; set; }
        public string adresse { get; set; }
        public Nullable<System.DateTime> dateInscription { get; set; }
    
        public virtual ICollection<emprunt> emprunts { get; set; }
    }
}
