//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tpdbEntities1 : DbContext
    {
        public tpdbEntities1()
            : base("name=tpdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adherent> adherent { get; set; }
        public DbSet<livre> livre { get; set; }
        public DbSet<theme> theme { get; set; }
        public DbSet<emprunt> emprunt { get; set; }
    }
}
