//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class emprunt
    {
        public Nullable<int> codeA { get; set; }
        public Nullable<int> codel { get; set; }
        public Nullable<System.DateTime> dateEmprunt { get; set; }
        public Nullable<System.DateTime> dateRetour { get; set; }
        public int id { get; set; }
    
        public virtual adherent adherent { get; set; }
        public virtual livre livre { get; set; }
    }
}
