//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class livre
    {
        public livre()
        {
            this.emprunts = new HashSet<emprunt>();
        }
    
        public int codel { get; set; }
        public string titre { get; set; }
        public string auteur { get; set; }
        public Nullable<int> nbEx { get; set; }
        public Nullable<int> codeTh { get; set; }
    
        public virtual theme theme { get; set; }
        public virtual ICollection<emprunt> emprunts { get; set; }
    }
}
